image: docker:latest

variables:
  # DOCKER_TLS_CERTDIR: ""
  DOCKER_TLS_CERTDIR: "/certs"
  REGISTRY: 294727153669.dkr.ecr.us-east-1.amazonaws.com
  AWS_DEFAULT_REGION: us-east-1
  APP_NAME: grp-21-frontend
  DOCKER_HOST: tcp://docker:2376

services:
  - docker:dind

stages:
    - build

build:
    stage: build
    tags:
      - ugrad
    image: 
      name: amazon/aws-cli
      entrypoint: [""]
    services:
      - docker:dind
    before_script:
        - amazon-linux-extras install docker
        - docker --version
        - aws --version
    script:
        - pwd
        - cd ./frontend
        - pwd
        - docker build -t $REGISTRY/$APP_NAME:latest .
        - aws ecr get-login-password | docker login --username AWS --password-stdin $REGISTRY
        - docker push $REGISTRY/$APP_NAME:latest
    only:
        - ci-cd
