image: node:latest

stages:
    - build

build:
    stage: build
    before_script:
        - 'command -v ssh-agent >/dev/null || (apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin)'
        - docker info
    script:
        - docker build -t grp-21-frontend .
    only:
        - ci-cd
