image: docker:20.10.16

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:20.10.16-dind

stages:
    - build

build:
    stage: build
    before_script:
        - docker info
    script:
        - docker build -t grp-21-frontend .
    only:
        - ci-cd
